//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CATALOGO : DbContext
    {
        public CATALOGO()
            : base("name=CATALOGO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<GRUPO> GRUPOS { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIOS { get; set; }
        public virtual DbSet<ACCION> ACCIONES { get; set; }
        public virtual DbSet<MODULO> MODULOS { get; set; }
        public virtual DbSet<SUBMODULO> SUBMODULOS { get; set; }
        public virtual DbSet<PARAMETRO> PARAMETROS { get; set; }
    }
}
